### ISSUE TITLE
Playlists Checklist

### ISSUE THREAD

**Issue by vickiychung** [vickiychung/Mockify#10]
# Albums / Artists

_April 14th, 2021_

## MVP
- [ ] Users can create, edit, and delete playlists
- [ ] Add song to playlist option available for each track on an album show page

## Functionality
- [ ] Backend: tables, models, controllers, jbuilder (index, show)
- [ ] Redux Loop: api util, actions, reducers (`entities.playlists` global state)
- [ ] Containers: PlaylistsIndexContainer, PlaylistShowContainer
- [ ] Presentational Components: PlaylistsIndex, PlaylistShow
- [ ] Show playlists on home page
- [ ] Playlists available via side bar

## Style
- [ ] Resembles actual Spotify styling

## Seeds
- [ ] Adequate seeds

**Comment by vickiychung** [comment]
Incomplete features

- remove track from playlist
- edit playlist
- delete playlist
- display current user's playlists when clicking on "Your Library" on the side bar

Bugs
- Routing acting weird when clicking back and forth on different playlist links on the side bar

**Comment by vickiychung** [comment]
To-do
- Playlist tracks sequence
- Sidebar your library: playlist index
