### ISSUE TITLE
Auth Checklist

### ISSUE THREAD

**Issue by samwalker191** [vickiychung/Mockify#2]
# User Auth
## Functionality
- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation
### Before Login
- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user
### After Login
- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in
## Style
- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production
## Seeds
- [x] Adequate and appropriate seeds

**Comment by vickiychung** [comment]
* Stuff getting cute off on iPhone screen (live app)
  * try em instead of px?
  * already have Viewport tag, but should I try adding media queries?

* How to attribute image and icon copyrights?

* Rainbow color for logo / favicon probably was a bad idea
  * maybe change later if there's extra time

**Comment by samwalker191** [comment]
Looks really good! 

A few comments on things I would recommend updating:
1. When you hit the enter button to submit the form for login or sign up, it ends up trying to log in as the demo user. You might have to move the demo user button outside of the form tag so that you can hit enter to submit the form with what is inputted, instead of the demo login. The demo login button should just be activated with a click.

2. For the styling on the form, you could make the input fields a little bigger and with a bit more padding. Additionally, the outline of the input fields should be a lighter gray. 

3. You could also vertically squish the form so that everything is not so spaced out.

Let me know if you have any questions

**Comment by samwalker191** [comment]
Looks good!
