### ISSUE TITLE
Search Checklist

### ISSUE THREAD

**Issue by vickiychung** [vickiychung/Mockify#20]
## Search
- [ ] Search by track name
- [ ] Search by artist name
- [ ] Search by album name
- [ ] Play individual track on search show page
