### ISSUE TITLE
Tracks Checklist

### ISSUE THREAD

**Issue by vickiychung** [vickiychung/Mockify#3]
# Tracks

## Functionality
- [x] Backend: tracks table, track model, tracks controller, jbuilder (index, show)
- [x] AWS: model association, jbuilder, rendering in presentational component
- [x] Redux Loop: tracks api util, tracks actions, tracks reducer
- [x] Containers: TracksIndexContainer
- [x] Presentational Components: TracksIndex, TracksIndexItem
- [x] Smooth, bug-free navigation
- [x] Tracks can be played on browser

## Style
- [x] Minimal styling for (temporary) tracks index page

## Seeds
- [x] Adequate and appropriate seeds

**Comment by vickiychung** [comment]
- Made "/tracks" protected route in my next feature branch

**Comment by samwalker191** [comment]
Looks good! Styling for the next MVPs will be more strict.

One thing that youll have to do is that you shouldnt need to scroll to see the webplayer. The tracks index should only take up enough space so that the webplayer can still be seen without scrolling. The tracks index should then be scrollable. Look into `overflow: scroll`!

**Comment by vickiychung** [comment]
Fixed css style with `overflow: scroll` in the new PR (merged)
