### ISSUE TITLE
Web Player Checklist

### ISSUE THREAD

**Issue by vickiychung** [vickiychung/Mockify#6]
# Web Player

_April 8th ~ 10th, 2021_

## MVP
- [x] Play music continuously while navigating through to different pages
- [x] Play, pause, next, back, shuffle functionalities
- [x] Indicate length of the song and current progress

## Functionality
- [x] Redux State: 
  - web player action
  - web player reducer
  - ui.webPlayer slice of global state (currentTrackId, playStatus, loopOn, shuffleOn)
- [x] Container: TracksIndex
  - add WebPlayer component in addition to TracksIndexItem
- [x] Presentational Component: WebPlayer
- [x] Play, pause
  - by clicking on individual tracks
  - by clicking on the web player
  - plays first song when clicking play for the first time
- [x] Next, previous
- [x] Shuffle (on/off)
- [x] Loop (on/off)
- [x] Volume slider
- [x] Playing progress seekbar
- [x] Display track name

## Style
- [x] Resembles actual Spotify web player styling

**Comment by vickiychung** [comment]
Bugs that need to be fixed:
- weird white cracks on the slider bars upon initial render
- not pausing correctly. Song starts from beginning when click play again (currentTime of audio tag gets reset to 0)

I'm going to change all the audio file paths of my track seeds to the same one for now, because I've already exceeded the AWS limit. Will change it back before deploying to production.

**Comment by vickiychung** [comment]
Fixed volume (default 30%)
