### ISSUE TITLE
Albums and Artists Checklist

### ISSUE THREAD

**Issue by vickiychung** [vickiychung/Mockify#8]
# Albums / Artists

_April 11th ~ 12th, 2021_

## MVP
- [ ] Users can play songs by selecting a track on the album page
- [ ] Users can view an artist page featuring the artist's albums

## Functionality
- [ ] Backend: tables, models, controllers, jbuilder (index, show)
- [ ] Redux Loop: api util, actions, reducers

## Style
- [ ] Resembles actual Spotify album page, artist page styling

## Seeds
- [ ] Albums, album covers (AWS)
- [ ] Artists

**Comment by vickiychung** [comment]
Bugs
- Web player can't pause (carried over from web player MVP)
- Web player component gets re-rendered every time
  - Components are not structured/designed correctly, but might not have time to change this before Friday 
- Global state `entities.artists` is technically incorrect (grabbing all artists)
  - `FetchArtist` was breaking in `album:show`, so had to change to `FetchArtists`, and then grab info with `artistId`

**Comment by vickiychung** [comment]
Minor bug:
- doesn't properly redirect back to home when typing in random url for album:show or artist:show (gets recognized as wildcard)
